name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students-test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres_drivenops_db:5432/students-test"
          file_name: "back-end/.env.test"
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_drivenops_app npm run test